ERROR - 2025-01-16 07:45:57 --> Error connecting to the database: ctype_digit(): Argument of type int will be interpreted as string in the future
CRITICAL - 2025-01-16 07:45:57 --> Unable to connect to the database.
Main connection [Postgre]: ctype_digit(): Argument of type int will be interpreted as string in the future
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp5\htdocs\peluit2025\public_html\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Home.php(25): CodeIgniter\BaseModel->findAll()
#5 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Home->index()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp5\htdocs\peluit2025\public_html\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp5\htdocs\peluit2025\public_html\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp5\\htdoc...')
#10 {main}
CRITICAL - 2025-01-16 07:45:57 --> Uncaught ErrorException: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in C:\xampp5\htdocs\peluit2025\public_html\system\Validation\FormatRules.php:253
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8192, 'strtolower(): P...', 'C:\\xampp5\\htdoc...', 253)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Validation\FormatRules.php(253): strtolower(NULL)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\HTTP\RequestTrait.php(151): CodeIgniter\Validation\FormatRules->valid_ip('::1')
#3 C:\xampp5\htdocs\peluit2025\public_html\app\Views\errors\html\error_exception.php(206): CodeIgniter\HTTP\Request->getIPAddress()
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(229): include('C:\\xampp5\\htdoc...')
#5 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#8 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 07:52:21 --> Error connecting to the database: ctype_digit(): Argument of type int will be interpreted as string in the future
CRITICAL - 2025-01-16 07:52:21 --> Unable to connect to the database.
Main connection [Postgre]: ctype_digit(): Argument of type int will be interpreted as string in the future
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp5\htdocs\peluit2025\public_html\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Home.php(25): CodeIgniter\BaseModel->findAll()
#5 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Home->index()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp5\htdocs\peluit2025\public_html\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp5\htdocs\peluit2025\public_html\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp5\\htdoc...')
#10 {main}
CRITICAL - 2025-01-16 07:52:21 --> Uncaught ErrorException: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in C:\xampp5\htdocs\peluit2025\public_html\system\Validation\FormatRules.php:253
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(8192, 'strtolower(): P...', 'C:\\xampp5\\htdoc...', 253)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Validation\FormatRules.php(253): strtolower(NULL)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\HTTP\RequestTrait.php(151): CodeIgniter\Validation\FormatRules->valid_ip('::1')
#3 C:\xampp5\htdocs\peluit2025\public_html\app\Views\errors\html\error_exception.php(206): CodeIgniter\HTTP\Request->getIPAddress()
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(229): include('C:\\xampp5\\htdoc...')
#5 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(232): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(116): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#7 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#8 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2025-01-16 10:38:35 --> Call to undefined function generateFormField()
#0 C:\xampp5\htdocs\peluit2025\public_html\system\View\View.php(214): include()
#1 C:\xampp5\htdocs\peluit2025\public_html\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Common.php(1097): CodeIgniter\View\View->render('admin/form-pela...', Array, true)
#3 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1030): view('admin/form-pela...', Array)
#4 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->detail_form('5')
#5 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2025-01-16 10:39:51 --> Invalid file: admin/form-pelayanan.php
#0 C:\xampp5\htdocs\peluit2025\public_html\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('admin/form-pela...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Common.php(1097): CodeIgniter\View\View->render('admin/form-pela...', Array, true)
#2 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1030): view('admin/form-pela...', Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->detail_form('9')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#5 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-01-16 10:39:56 --> Invalid file: admin/form-pelayanan.php
#0 C:\xampp5\htdocs\peluit2025\public_html\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('admin/form-pela...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Common.php(1097): CodeIgniter\View\View->render('admin/form-pela...', Array, true)
#2 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1030): view('admin/form-pela...', Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->detail_form('5')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#5 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2025-01-16 10:40:14 --> Invalid file: admin/form-pelayanan.php
#0 C:\xampp5\htdocs\peluit2025\public_html\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('admin/form-pela...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Common.php(1097): CodeIgniter\View\View->render('admin/form-pela...', Array, true)
#2 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1030): view('admin/form-pela...', Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->detail_form('5')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#5 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2025-01-16 10:42:39 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 2: FROM &quot;form_fields&quot;
             ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'SELECT *\nFROM "...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1037): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->get_form_fields('5')
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:39 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 2: FROM &quot;form_fields&quot;
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'SELECT *\nFROM "...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1037): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->get_form_fields('5')
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:39 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:42:52 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:52 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:52 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:42:53 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:53 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:53 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:42:54 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:54 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:54 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:42:54 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:54 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:54 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:42:54 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:54 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:54 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:42:54 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:54 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:54 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:42:55 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:55 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:55 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:42:55 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:55 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:42:55 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:43:03 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 2: FROM &quot;form_fields&quot;
             ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'SELECT *\nFROM "...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1037): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->get_form_fields('10')
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:43:03 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 2: FROM &quot;form_fields&quot;
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'SELECT *\nFROM "...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1037): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->get_form_fields('10')
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:43:03 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:43:29 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 2: FROM &quot;form_fields&quot;
             ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'SELECT *\nFROM "...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1037): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->get_form_fields('11')
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:43:29 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 2: FROM &quot;form_fields&quot;
             ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'SELECT *\nFROM "...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('SELECT *\nFROM "...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM "...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1443): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM "...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1037): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->get_form_fields('11')
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:43:29 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:45:46 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:45:46 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:45:46 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:45:47 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:45:47 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:45:47 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:45:47 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:45:47 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:45:47 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2025-01-16 10:45:47 --> ErrorException: pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^ in C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php:136
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:45:47 --> pg_query(): Query failed: ERROR:  relation &quot;form_fields&quot; does not exist
LINE 1: INSERT INTO &quot;form_fields&quot; (&quot;id_pelayanan&quot;, &quot;label&quot;, &quot;type&quot;, ...
                    ^
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp5\\htdoc...', 136, Array)
#1 C:\xampp5\htdocs\peluit2025\public_html\system\Database\Postgre\Connection.php(136): pg_query(Resource id #125, 'INSERT INTO "fo...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "fo...')
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "fo...')
#4 C:\xampp5\htdocs\peluit2025\public_html\system\Database\BaseBuilder.php(1759): CodeIgniter\Database\BaseConnection->query('INSERT INTO "fo...', Array, false)
#5 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(1057): CodeIgniter\Database\BaseBuilder->insert(Array)
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->save_form_field()
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#8 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2025-01-16 10:45:47 --> Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: "Type is not supported". in C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php:41
Stack trace:
#0 C:\xampp5\htdocs\peluit2025\public_html\system\Format\JSONFormatter.php(41): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Array)
#2 C:\xampp5\htdocs\peluit2025\public_html\system\API\ResponseTrait.php(99): CodeIgniter\Debug\Exceptions->format(Array)
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Debug\Exceptions.php(110): CodeIgniter\Debug\Exceptions->respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2025-01-16 11:28:58 --> View themes, no current section.
#0 C:\xampp5\htdocs\peluit2025\public_html\app\Views\admin\tiket.php(593): CodeIgniter\View\View->endSection()
#1 C:\xampp5\htdocs\peluit2025\public_html\system\View\View.php(214): include('C:\\xampp5\\htdoc...')
#2 C:\xampp5\htdocs\peluit2025\public_html\system\View\View.php(217): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\xampp5\htdocs\peluit2025\public_html\system\Common.php(1097): CodeIgniter\View\View->render('admin/tiket', Array, true)
#4 C:\xampp5\htdocs\peluit2025\public_html\app\Controllers\Admin.php(176): view('admin/tiket', Array)
#5 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(824): App\Controllers\Admin->tiket_page()
#6 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp5\htdocs\peluit2025\public_html\system\CodeIgniter.php(318): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp5\htdocs\peluit2025\public_html\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
